### ISSUE TITLE
What is ifconfig docker0?

### ISSUE THREAD

**Issue by squarism** [mdevilliers/docker-rediscluster#1]
In the script, you find the docker host ip with the `ifconfig docker0` trick.  What is that doing?  There's no such interface when using boot2docker on osx.  That's ok, I'm just wondering if I can workaround it but I don't know what docker0's purpose is.  I didn't know the host IP was significant in docker.  On Linux, is an IP created and then your script uses that IP to identify hosts?

Maybe this is a neat trick to connect machines because that's sort of tricky with docker (why compose was built)?

**Comment by mdevilliers** [comment]
Looking at the script again, its been a while, the ifconfig docker0 line gets an ip address to use as an assembly point for all of the sentinels.

This is usually 172.16.42.1 - it will be this in the majority of cases except when it is [not](https://github.com/docker/docker/issues/1143).

The trick is that all of the containers running inside docker will be able to see this address as the docker0 interface is available to them.

I hope that makes sense?

I've never played with boot2docker but maybe you could try hardcoding the ip address (either 172.16.42.1 or another) in to the script?

**Comment by squarism** [comment]
Yeah, hardcoding the script won't work.  That IP doesn't exist on my box.  It can't be pinged, it causes it to fail etc.  I'm not sure there is a portable way to pull this off.  Thanks, I'm going to keep trying and use your scripts as reference.  :monkey_face:

**Comment by dragsbruh** [comment]
that thing replaced my ethernet and i cant connect to the internet

**Comment by shitcodebykaushik** [comment]
I think this doesnt work as of now
