### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by rfyiamcool** [mdevilliers/docker-rediscluster#3]
Currently the cluster is fixed at 6 nodes, 3 master with each one slave. This configuration should should be dynamic and allow for change to possibly test different scenarios.

**Comment by mdevilliers** [comment]
A fork that you might be interested in is https://github.com/PlanitarInc/docker-rediscluster - this has the ability to create dynamic topologies - at the expense of a bit more complexity.

If this doesn't meet your needs I'd love to see a pull request?

Mark
